### ISSUE TITLE
Installation fails for rke2 with k8s 1.23 with Kubelet binary not identified

### ISSUE THREAD

**Issue by lsoica** [nestybox/sysbox#614]
For RKE v1.23.14+rke2r1
```
$ systemctl status kubelet-config-helper.service
● kubelet-config-helper.service - Kubelet config service
     Loaded: loaded (/lib/systemd/system/kubelet-config-helper.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-12-12 17:35:25 UTC; 1min 10s ago
    Process: 244805 ExecStart=/bin/sh -c /usr/local/bin/kubelet-config-helper.sh (code=exited, status=1/FAILURE)
   Main PID: 244805 (code=exited, status=1/FAILURE)

Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + kubelet_bin=
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + '[' -z '' ']'
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + die 'Kubelet binary not identified.'
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + msg='Kubelet binary not identified.'
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + echo 'ERROR: Kubelet binary not identified.'
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: ERROR: Kubelet binary not identified.
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 sh[244806]: + exit 1
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 systemd[1]: kubelet-config-helper.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 systemd[1]: kubelet-config-helper.service: Failed with result 'exit-code'.
Dec 12 17:35:25 gitpod-nci-buc-ds-jdsu-net-1 systemd[1]: Failed to start Kubelet config service.
```

**Comment by rodnymolina** [comment]
@lsoica, thanks for filing an issue for this.

We fixed a few issues related to RKE2 as part of issue #567. I believe the work we've done there should also fix this issue you just reported. I'll be building a test image within the next few days to verify my assumptions. Will ping you when done.

**Comment by lsoica** [comment]
OK, cool. In the meantime, what are the k8s distros that still work with the current sysbox version?

**Comment by ctalledo** [comment]
> OK, cool. In the meantime, what are the k8s distros that still work with the current sysbox version?

See [here](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#kubernetes-distro-requirements) please. 

We will be adding support for K8s v1.24 and later very soon.

**Comment by andreasrossa** [comment]
For me this issue still persists. 

I am running RKE2 v1.23.15+rke2r1 on a Ubuntu 22.04.2 LTS node with kernel version  5.15.0-67-generic.

I have also tried the "ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev" deploy image that @rodnymolina mentioned in #567
but am still getting the same error @lsoica is describing.

Any updates on this?

**Comment by rodnymolina** [comment]
@andreasrossa, @lsoica, I'm unable to reproduce this one after making use of the same exact RKE2 release mentioned above (v1.23.15+rke2r1) or any other more-recent version. The only difference between my setup and @andreasrossa's one is that my kernel is older (5.4), but that shouldn't play any role in the problem at hand.

Could you please verify that problem can be still reproduced on your end? I would suggest to try with the latest v0.6.1 pre-release image (`registry.nestybox.com/nestybox/sysbox-deploy-k8s:v0.6.1-prerel`), even though there are no differences between this one and the previous one you tried (`ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev`) in regards to rke2.

**Comment by rodnymolina** [comment]
As mentioned above, I haven't been able to reproduce this with the latest v0.6.1 release. Closing issue now. Please re-open if you run into this one again.
